{% set version = '0.20.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-git2r
  version: {{ version|replace("-", "_") }}

source:
  fn: git2r_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/git2r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/git2r/git2r_{{ version }}.tar.gz
  sha256: 86a0ffd6734f61d0720f3176e286d1231c3da4e3afe42b182b8b2abd657c0fdf


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: getPass
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}automake          # [not win]
    - {{posix}}pkg-config
    - {{posix}}make

  host:
    - r-base
    - {{native}}libssh2 1.*      # [not win]
    - {{native}}zlib 1.2.8       # [win]
    - {{native}}zlib             # [not win]
    - {{native}}openssl
    - {{native}}curl             # [win]
    - {{native}}libcurl          # [not win]
    - {{native}}libiconv         # [osx]

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - {{native}}libssh2 1.*      # [not win]
    - {{native}}zlib 1.2.8       # [win]
    - {{native}}openssl          # [win]
    - {{native}}curl             # [win]
    - {{native}}libcurl          # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('git2r')"           # [not win]
    - "\"%R%\" -e \"library('git2r')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/git2r
  license: GPL-2
  summary: Interface to the 'libgit2' library, which is a pure C implementation of the 'Git'
    core methods. Provides access to 'Git' repositories to extract data and running
    some basic 'Git' commands.
  license_family: GPL2

extra:
  recipe-maintainers:
    - jdblischak
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: git2r
# Title: Provides Access to Git Repositories
# Description: Interface to the 'libgit2' library, which is a pure C implementation of the 'Git' core methods. Provides access to 'Git' repositories to extract data and running some basic 'Git' commands.
# Version: 0.20.0
# License: GPL-2
# Copyright: See COPYRIGHTS file.
# URL: https://github.com/ropensci/git2r
# BugReports: https://github.com/ropensci/git2r/issues
# Maintainer: Stefan Widgren <stefan.widgren@gmail.com>
# Author: See AUTHORS file.
# Imports: graphics, utils
# Depends: R (>= 3.0.2), methods
# Suggests: getPass
# Type: Package
# LazyData: true
# Biarch: true
# NeedsCompilation: yes
# SystemRequirements: zlib headers and library. OpenSSL headers and library. LibSSH2 (optional on non-Windows) to enable the SSH transport.
# Collate: 'S4_classes.r' 'blame.r' 'blob.r' 'branch.r' 'bundle_r_package.r' 'checkout.r' 'commit.r' 'config.r' 'contributions.r' 'credential.r' 'diff.r' 'fetch.r' 'git2r.r' 'index.r' 'libgit2.r' 'merge.r' 'note.r' 'odb.r' 'plot.r' 'pull.r' 'punch_card.r' 'refspec.r' 'push.r' 'reference.r' 'reflog.r' 'remote.r' 'repository.r' 'reset.r' 'revparse.r' 'signature.r' 'stash.r' 'status.r' 'tag.r' 'time.r' 'tree.r' 'when.r'
# RoxygenNote: 6.0.1
# Packaged: 2017-12-17 19:25:41 UTC; stefan
# Repository: CRAN
# Date/Publication: 2017-12-17 22:56:21 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
