travis:
  secure:
    BINSTAR_TOKEN: LmGyyNrqBMDswE7992TwP5K8a3pAUYqNvBNjwBLyp68S/93lwxKb4OtFYrwOZG/qGUON6YujfG6mq7798XwpoGrHqYcNubJypfnPT2Xp5CEbdiUoAxa09IKmrzr6H29G0yPlXYgzumo3zCC1BUJIXGefIE/zDe1Qxz7QbTg/Nokk6L7/RiktpuXOVXEidY4Py5oWdOq0t31Z8oOjReqRNhzg9UW1M6ZRlVP/wwzsc9Ltosuf5ytkNovgxvFf0t5YfWGFNANJghbjU+XNnpcgqR+HE3ekzcj04ak00WjwTytpPGNS9hchrswymYTYfDPZMqJBUHkbsWmREdiOyGNmeZ6vReFj0ZuJHHw3Nbr1KQEdtg0CZxwbk/3un0fAhvLFPZU7Ur7CbFoc9BUZCFWb5h52lnQvFBuFvtIWZSLpG3GbtqPBjpzwndfZ9bKwIEftG3ZymMj8xNpl52bvOVayiJ6KvdB0IBixCPLjt1uGvIzUSVhnq0wACoPKPnjssRDmFVVPqy3eJdnWPQmH4fDT9cqaUd/fGK9kmXF5uNFiHSe1W9wPfe2MIhR13k6K/m2USqvAr2JoMwj/0R4ksYilH2LqACBQwk1ZUA4X+ud7HWME0CLHkXa6H1B6pj1fR3+dBLW730FP3NXUR/qYYP/5/cfFMYCq/lCR9SLgggKfEsw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
