travis:
  secure:
    BINSTAR_TOKEN: JKQRuJKmRlmJJKF1MT3qII1T7BplN+lvTWYdlD54+x0PwbaQF0q5KX1f0BZHHs7Um1T2Hy/+zPLXDg+NIF904khHlL+ysLXC0D5cEVlpHOH+v2qs2ZUzmTTSN3LmfcDkXnyo8N6suuI8yHe/zCvEpwJmlCtNFukna9jpzJnAAH5nw5M8Apsh4XrF6jLq5YsUwp178z8TDgqaTlhBcYXpjXQO+RknUD7LNk9Rgj3u1Dh9RmT8HetnOqKk9R5DqlbOhOlCJpaNxrq9f59ZCqy5SOg+ZRvcQLlfe2VBUYlT384IXBgxfvbIp6Ds8MX+xKJ2SdfxpICF87io0sFHm8HiSYmrIL27gPv9E+KZ3hkekGnSAx54OUGafpQ4+L0iPuhoazDAgUUXBpJWQy/1ibjsR07u04i0uvzET9UYIyJkJAJGgwKVLrTuFob3Ek6/063ARr+bwyy7aON3LcwoAf6zWpDqp1KmOCl8Nn0x8X18syRrYcZduECM7MdmYFO396dLxEPPFHEqipVn1dLuzr6OW/8il26MoKJBqeLntzcOKxel6rPIQFmV42fnyYUJGiDj/yWjUwbMHGI1vu0eOIHw8rEV6a3DdBp4PjSTjhGm2ldkUxD845RCb6g9WLWFQNk1VuZTthH5JrhzDzOHissa8eMw4onV/fv22ehfx5NNdI4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
