travis:
  secure:
    BINSTAR_TOKEN: WnpGHwkHJ8oC9/0X7lkaGxeWhBgrRyQf21XXL620XbC/DVZixOKzNEMCnSnU8Cq+xVc2SVM30DlVSX0LLxsYekk7Rw/09HoxUreDsUKbyTlMOWl28BnEdkzXPgu5N5p2msNXweCwNCM5rmO+ZJxsKNO+Yx0so7gXocw7lFsq4p8jVT0A6xiru2Xo463l3y3TCDwua4lzsAVDdvKKTh4qX+Y8VXWD4HRckuvYLOJsCRyIXHYtlt+dduPR4EMm7EW5/rAmoarJqfpTwn6nSwHZshqRGuUyqgZg+drNMDMwHJ86/mC6edfJFZDGcn9x60OQJWFPTgfOOCtObsMkmpzk2veQmhWxZaxhwohgavR4pp9F5SLVQyG9PZFXFbBPtL4kZoJj3k/2RjfrbBFiumsrqBv1Yu2aVmnsCcFaVbb7nendCIYAYWpIEjgE/lI4iSMbKYaCqaZISKBHXTrBEnyGbaN9GD4mQufmMvKVLTRH4PKH8n32SygEPgz+kHVKEDqxq6vLtzmQDO5Fe2Q3mUvuDLKZe1CkOaO3YVVAMlaaUHlmCSfjSMg2e6A1Uf+lR9S/efMriIv/yq8DKvPnS05Iz1mogXhlg2dkVc7ccYLduhuT175Hqhy69X6Q/d3oYIpYTyOJ36AOnF9whWXaS8lntiFgNFt9tgat6hfnfgQ76uA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
