travis:
  secure:
    BINSTAR_TOKEN: NxmM6DGL3Lb+LeU10NVlNUUr4NoqrMed0DTajBMIWJ4QrB6q1r28YOSliiWFhGMjcHo70CrB574fndZbNQ/WBgEUWBuKgjmxNX58hkufxGnadh4abbR8TYVtTn3KFiWOYuAma4D9qppDNEaSKN2oFZ1IS2yQWG8EWjRjh4rJg2pgTBpLH18eq7hd3tTVErlE40mDmOlbmQQERolRxjYCHHGO3m415qoT4QlfjVk/2vRKfds81JOutcMaC9juVe9D/rKCvBuhInERwnthpBQSxaJ32fMHFVMRmw54h1yxGvYY+krTYs+ZtSYvyOZ4VvNezP5TaxEwB+AfxzSr950ZyXd4joM496QAAWfkYPKgk2x1Rm6wYr4wJd/K74mX7Y7YMa5ryfc2Md0CbVCUPl59oMPSOXEPfRzH2Agl89OsqDPr5eD3nz7LiaISvZ4Um2yjEgGMgFf7ITnAmI5hlnffRUwMpu8Gu7mbIM1dEk2VGUVggmZ6vD96AR86avACkBQC/wJT3H2H2R0PLfqUPggOSCTC6L5We8rRSmb9j50QyRRPI1Ly1MDhsrMjIYFjzBTkLJ0UtBbuymYV9bZ+E/ARR5jECdIK5Dw60MYaQtYtr10zXpNYcNXJcP1wFBI0OXv5FKdR06G/QZxn4o75fu05aYInoeaD9Hh+wzxBfciNHYs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
